version: "3.9"
services:
  crud-api:
    build:
      context: .
      dockerfile: ./Crud.Api/Dockerfile
    container_name: crud.api
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:5000"
      WriteConnection: "Host=postgres;Port=5432;Database=crud_db;Username=postgres;Password=postgres"
    ports:
      - "5003:5000"

  postgres:
    image: postgres:16
    container_name: crud.postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "crud_db"
    ports:
      - "5434:5432"
    volumes:
      - postgres_data2:/var/lib/postgresql/data

volumes:
  postgres_data2: